export const data = [
  {
    id: 1,
    title: "Video title: a medium video title 1",
    channel: "Channel title 1",
    views: "123K",
    date: "1 hour ago",
  },
  {
    id: 2,
    title: "Video. Video title: a long video title. New video 2",
    channel: "Channel title 2",
    views: "13K",
    date: "3 hours ago",
  },
  {
    id: 3,
    title: "Video 3",
    channel: "Channel title 3",
    views: "1K",
    date: "1 hour ago",
  },
  {
    id: 4,
    title: "Video 4",
    channel: "Channel title 4",
    views: "12",
    date: "12 hours ago",
  },
  {
    id: 5,
    title: "Video 5",
    channel: "Channel title 5",
    views: "1M",
    date: "1 hour ago",
  },
  {
    id: 6,
    title: "Video 6",
    channel: "Channel title 6",
    views: "13K",
    date: "1 min ago",
  },
  {
    id: 7,
    title: "Video 7",
    channel: "Channel title 7",
    views: "12",
    date: "1 day ago",
  },
  {
    id: 8,
    title: "Video. Video title: a long video title. New video 8",
    channel: "Channel title 8",
    views: "1K",
    date: "1 week ago",
  },
  {
    id: 9,
    title: "Video 9",
    channel: "Channel title 9",
    views: "300K",
    date: "1 hour ago",
  },
  {
    id: 10,
    title: "Video 10",
    channel: "Channel title 10",
    views: "123K",
    date: "1 hour ago",
  },
  {
    id: 11,
    title: "Video 11",
    channel: "Channel title 11",
    views: "987",
    date: "1 day ago",
  },
];
